"""initial schema

Revision ID: 41fb2b440ff4
Revises: 
Create Date: 2026-10-01 07:37:27.074117
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('before', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('after', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('station_id', sa.String(length=16), nullable=False),
    sa.Column('object_id', sa.String(length=48), nullable=False),
    sa.Column('allowed_event_types', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('period_s', sa.Float(), nullable=False),
    sa.Column('stale_after_s', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_mode', sa.String(length=16), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seq', sa.BigInteger(), nullable=True),
    sa.Column('last_boot_id', sa.String(length=48), nullable=True),
    sa.Column('health', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domain_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('endpoint', sa.String(length=160), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', 'user_id')
    )
    op.create_table('incidents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('station_id', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('object_type', sa.String(length=16), nullable=True),
    sa.Column('object_id', sa.String(length=32), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('index_configs',
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_table('index_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('model_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('real_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.Column('components', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('quality', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manual_overrides',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('object_id', sa.String(length=48), nullable=False),
    sa.Column('attribute', sa.String(length=32), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observations',
    sa.Column('object_id', sa.String(length=48), nullable=False),
    sa.Column('attribute', sa.String(length=32), nullable=False),
    sa.Column('device_id', sa.String(length=48), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quality', sa.String(length=16), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('object_id', 'attribute', 'device_id')
    )
    op.create_table('plan_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('base_state_version', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('solver', sa.String(length=32), nullable=False),
    sa.Column('solver_status', sa.String(length=32), nullable=False),
    sa.Column('solve_ms', sa.Float(), nullable=False),
    sa.Column('summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('changes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('assignments', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('assumptions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('applied_by', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('station_id', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('affected', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('action', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('effect', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('computed_real_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('based_on_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.String(length=16), nullable=False),
    sa.Column('resource_key', sa.String(length=64), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('purpose', sa.String(length=160), nullable=False),
    sa.Column('train_id', sa.String(length=32), nullable=True),
    sa.Column('operation_id', sa.String(length=32), nullable=True),
    sa.Column('request_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_res_key_time', 'reservations', ['resource_key', 'start_at'], unique=False)
    op.create_table('sim_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('running', sa.Boolean(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('scenario', sa.String(length=48), nullable=False),
    sa.Column('station_config', sa.String(length=16), nullable=False),
    sa.Column('plan_state_version', sa.BigInteger(), nullable=False),
    sa.Column('world', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('scheduled_events', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('seq_counter', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('state_deltas',
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('real_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_index(op.f('ix_state_deltas_real_time'), 'state_deltas', ['real_time'], unique=False)
    op.create_table('state_snapshots',
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('real_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_index(op.f('ix_state_snapshots_real_time'), 'state_snapshots', ['real_time'], unique=False)
    op.create_table('stations',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telemetry_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=48), nullable=False),
    sa.Column('station_id', sa.String(length=16), nullable=False),
    sa.Column('object_id', sa.String(length=48), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sequence_number', sa.BigInteger(), nullable=False),
    sa.Column('boot_id', sa.String(length=48), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('quality', sa.String(length=16), nullable=False),
    sa.Column('source_mode', sa.String(length=16), nullable=False),
    sa.Column('schema_version', sa.String(length=8), nullable=False),
    sa.Column('disposition', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'event_id', name='uq_telemetry_device_event')
    )
    op.create_index('ix_telemetry_object', 'telemetry_events', ['object_id', 'observed_at'], unique=False)
    op.create_index('ix_telemetry_received', 'telemetry_events', ['received_at'], unique=False)
    op.create_table('telemetry_rejects',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('topic', sa.String(length=160), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('reason_code', sa.String(length=48), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('raw', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trains',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('number', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('origin_station_id', sa.String(length=16), nullable=True),
    sa.Column('destination_station_id', sa.String(length=16), nullable=True),
    sa.Column('arrival_side', sa.String(length=8), nullable=False),
    sa.Column('departure_side', sa.String(length=8), nullable=False),
    sa.Column('wagons_count', sa.Integer(), nullable=False),
    sa.Column('length_m', sa.Float(), nullable=True),
    sa.Column('loco_length_m', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('scheduled_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_track_id', sa.String(length=32), nullable=True),
    sa.Column('transfer_request_id', sa.String(length=32), nullable=True),
    sa.Column('cargo', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfer_requests',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('number', sa.String(length=16), nullable=False),
    sa.Column('from_station_id', sa.String(length=16), nullable=False),
    sa.Column('to_station_id', sa.String(length=16), nullable=False),
    sa.Column('wagons_count', sa.Integer(), nullable=False),
    sa.Column('wagon_kind', sa.String(length=16), nullable=True),
    sa.Column('train_length_m', sa.Float(), nullable=True),
    sa.Column('cargo', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('split_allowed', sa.Boolean(), nullable=False),
    sa.Column('desired_departure', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_check', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('last_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_check_version', sa.Integer(), nullable=True),
    sa.Column('train_id', sa.String(length=32), nullable=True),
    sa.Column('parent_id', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('capacity_rules',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('station_id', sa.String(length=16), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('unit', sa.String(length=48), nullable=False),
    sa.Column('period', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=160), nullable=False),
    sa.Column('rule_text', sa.Text(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('policy', sa.String(length=16), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_windows',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('station_id', sa.String(length=16), nullable=False),
    sa.Column('object_type', sa.String(length=16), nullable=False),
    sa.Column('object_id', sa.String(length=32), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('station_id', sa.String(length=16), nullable=False),
    sa.Column('train_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.String(length=32), nullable=True),
    sa.Column('from_track_id', sa.String(length=32), nullable=True),
    sa.Column('side', sa.String(length=8), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('requirements', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('resource_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('route_nodes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('planned_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('planned_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('not_before', sa.DateTime(timezone=True), nullable=True),
    sa.Column('forecast_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('forecast_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('extra_delay_min', sa.Integer(), nullable=False),
    sa.Column('reserved', sa.Boolean(), nullable=False),
    sa.Column('plan_version', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_operations_train', 'operations', ['train_id', 'seq'], unique=False)
    op.create_table('parks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('station_id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plans',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('station_id', sa.String(length=16), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('target_wagons', sa.Integer(), nullable=False),
    sa.Column('actual_base_wagons', sa.Integer(), nullable=False),
    sa.Column('policy', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resources',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('station_id', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('home_zone_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topology_nodes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('station_id', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('track_connections',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('station_id', sa.String(length=16), nullable=False),
    sa.Column('from_node', sa.String(length=32), nullable=False),
    sa.Column('to_node', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('track_id', sa.String(length=32), nullable=True),
    sa.Column('length_m', sa.Float(), nullable=False),
    sa.Column('points', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wagons',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('train_id', sa.String(length=32), nullable=True),
    sa.Column('number', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('length_m', sa.Float(), nullable=True),
    sa.Column('loaded', sa.Boolean(), nullable=False),
    sa.Column('condition', sa.String(length=16), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('last_checkpoint', sa.String(length=32), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zones',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('station_id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('track_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_shifts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resource_id', sa.String(length=32), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('station_id', sa.String(length=16), nullable=False),
    sa.Column('park_id', sa.String(length=32), nullable=False),
    sa.Column('number', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('useful_length_m', sa.Float(), nullable=True),
    sa.Column('allowed_train_kinds', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('from_node', sa.String(length=32), nullable=False),
    sa.Column('to_node', sa.String(length=32), nullable=False),
    sa.Column('zone_id', sa.String(length=32), nullable=True),
    sa.Column('points', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('electrified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['park_id'], ['parks.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Запрет двойного бронирования на уровне БД: активные резервы одного ресурса не могут
    # пересекаться по времени. Срабатывает и при конкурентных транзакциях.
    op.execute("""
        ALTER TABLE reservations ADD CONSTRAINT reservations_no_overlap
        EXCLUDE USING gist (resource_key WITH =, tstzrange(start_at, end_at, '[)') WITH &&)
        WHERE (status = 'confirmed')
    """)
    # ### end Alembic commands ###


def downgrade():
    op.execute("ALTER TABLE reservations DROP CONSTRAINT IF EXISTS reservations_no_overlap")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracks')
    op.drop_table('resource_shifts')
    op.drop_table('zones')
    op.drop_table('wagons')
    op.drop_table('track_connections')
    op.drop_table('topology_nodes')
    op.drop_table('resources')
    op.drop_table('plans')
    op.drop_table('parks')
    op.drop_index('ix_operations_train', table_name='operations')
    op.drop_table('operations')
    op.drop_table('maintenance_windows')
    op.drop_table('capacity_rules')
    op.drop_table('users')
    op.drop_table('transfer_requests')
    op.drop_table('trains')
    op.drop_table('telemetry_rejects')
    op.drop_index('ix_telemetry_received', table_name='telemetry_events')
    op.drop_index('ix_telemetry_object', table_name='telemetry_events')
    op.drop_table('telemetry_events')
    op.drop_table('stations')
    op.drop_index(op.f('ix_state_snapshots_real_time'), table_name='state_snapshots')
    op.drop_table('state_snapshots')
    op.drop_index(op.f('ix_state_deltas_real_time'), table_name='state_deltas')
    op.drop_table('state_deltas')
    op.drop_table('sim_state')
    op.drop_index('ix_res_key_time', table_name='reservations')
    op.drop_table('reservations')
    op.drop_table('recommendations')
    op.drop_table('plan_versions')
    op.drop_table('observations')
    op.drop_table('manual_overrides')
    op.drop_table('index_snapshots')
    op.drop_table('index_configs')
    op.drop_table('incidents')
    op.drop_table('idempotency_keys')
    op.drop_table('domain_events')
    op.drop_table('devices')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
